# Generated by Django 4.2.29 on 2026-03-26 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='职位名称')),
                ('address', models.CharField(max_length=100, verbose_name='工作城市')),
                ('type', models.CharField(max_length=100, verbose_name='岗位类型')),
                ('educational', models.CharField(max_length=50, verbose_name='学历要求')),
                ('workExperience', models.CharField(max_length=100, verbose_name='工作经验')),
                ('workTag', models.CharField(blank=True, max_length=500, null=True, verbose_name='技能标签')),
                ('salary', models.CharField(max_length=100, verbose_name='薪资范围')),
                ('salaryMonth', models.CharField(blank=True, max_length=50, null=True, verbose_name='年终奖')),
                ('companyTags', models.CharField(blank=True, max_length=500, null=True, verbose_name='公司福利')),
                ('hrWork', models.CharField(blank=True, max_length=100, null=True, verbose_name='HR职位')),
                ('hrName', models.CharField(blank=True, max_length=100, null=True, verbose_name='HR姓名')),
                ('pratice', models.BooleanField(default=False, verbose_name='是否实习')),
                ('companyTitle', models.CharField(max_length=200, verbose_name='公司名称')),
                ('companyAvatar', models.CharField(blank=True, max_length=500, null=True, verbose_name='公司头像')),
                ('companyNature', models.CharField(blank=True, max_length=100, null=True, verbose_name='公司性质')),
                ('companyStatus', models.CharField(blank=True, max_length=100, null=True, verbose_name='融资状态')),
                ('companyPeople', models.CharField(blank=True, max_length=100, null=True, verbose_name='公司规模')),
                ('detailUrl', models.CharField(blank=True, max_length=500, null=True, verbose_name='详情地址')),
                ('companyUrl', models.CharField(blank=True, max_length=500, null=True, verbose_name='公司地址')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dist', models.CharField(blank=True, max_length=100, null=True, verbose_name='行政区')),
            ],
            options={
                'verbose_name': '招聘信息',
                'verbose_name_plural': '招聘信息',
                'db_table': 'jobinfo',
                'ordering': ['-createTime'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational', models.CharField(blank=True, max_length=50, null=True, verbose_name='学历')),
                ('workExperience', models.CharField(blank=True, max_length=100, null=True, verbose_name='工作经验')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='意向城市')),
                ('work', models.CharField(blank=True, max_length=100, null=True, verbose_name='意向岗位')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户扩展信息',
                'verbose_name_plural': '用户扩展信息',
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='收藏次数')),
                ('viewTime', models.DateTimeField(auto_now_add=True, verbose_name='浏览时间')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.jobinfo', verbose_name='职位')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '浏览记录',
                'verbose_name_plural': '浏览记录',
                'db_table': 'history',
                'ordering': ['-viewTime'],
            },
        ),
    ]
