# Generated by Django 4.2.29 on 2026-03-26 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="createTime",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="创建时间"
            ),
            preserve_default=False,
        ),
    ]
